/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai_tap_lon;

import java.io.FileWriter;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Nhuan's computer
 */
public class DangNhap extends javax.swing.JFrame {

    /**
     * Creates new form DangNhap
     */
    public DangNhap() {
        setLocation(this.getHeight() + 200, this.getWidth());
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        taikhoan = new javax.swing.JTextField();
        matkhau = new javax.swing.JPasswordField();
        welcome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dangnhap = new javax.swing.JButton();
        Backgroud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Người dùng đăng nhập");

        jPanel1.setLayout(null);

        taikhoan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(taikhoan);
        taikhoan.setBounds(610, 390, 290, 40);

        matkhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        matkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matkhauActionPerformed(evt);
            }
        });
        jPanel1.add(matkhau);
        matkhau.setBounds(610, 470, 290, 40);

        welcome.setBackground(new java.awt.Color(255, 102, 0));
        welcome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        welcome.setForeground(new java.awt.Color(255, 255, 255));
        welcome.setText("Welcome");
        welcome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                welcomeActionPerformed(evt);
            }
        });
        jPanel1.add(welcome);
        welcome.setBounds(560, 640, 109, 39);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tài Khoản");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(480, 400, 80, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mật khẩu");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(480, 480, 80, 19);

        dangnhap.setBackground(new java.awt.Color(255, 102, 0));
        dangnhap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dangnhap.setForeground(new java.awt.Color(255, 255, 255));
        dangnhap.setText("Đăng nhập");
        dangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangnhapActionPerformed(evt);
            }
        });
        jPanel1.add(dangnhap);
        dangnhap.setBounds(790, 640, 114, 39);

        Backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bai_tap_lon/Đăng nhập.png"))); // NOI18N
        jPanel1.add(Backgroud);
        Backgroud.setBounds(10, 10, 940, 788);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Đăng nhập");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void matkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matkhauActionPerformed
        String s=taikhoan.getText();
        String mk = matkhau.getText();
        try {
            CSDL.WriteIDToFile(s);
        } catch (IOException ex) {
            Logger.getLogger(DangNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            if(CSDL.statement_kiemtrataikhoanvamatkhau(s, mk)==true && CSDL.adminOrNot(s, mk) == false){
                TrangChuUser tcuse=new TrangChuUser();
                tcuse.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Sai ten dang nhap hoac mat khau, tai khoan chua ton tai");
            }
        } catch (SQLException ex) {
            Logger.getLogger(DangNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_matkhauActionPerformed
    //ấn vào welcome về welcome
    private void welcomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_welcomeActionPerformed
        Welcome wel=new Welcome();
        wel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_welcomeActionPerformed
    //ấn vào đăng nhập để vào trang chủ người dùng
    private void dangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangnhapActionPerformed
        String s=taikhoan.getText();
        String mk = matkhau.getText();
        try {
            CSDL.WriteIDToFile(s);
        } catch (IOException ex) {
            Logger.getLogger(DangNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            if(CSDL.statement_kiemtrataikhoanvamatkhau(s, mk)==true && CSDL.adminOrNot(s, mk) == false){
                TrangChuUser tcuse=new TrangChuUser();
                tcuse.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Sai ten dang nhap hoac mat khau, tai khoan chua ton tai");
            }
        } catch (SQLException ex) {
            Logger.getLogger(DangNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dangnhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backgroud;
    public javax.swing.JButton dangnhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField matkhau;
    public static javax.swing.JTextField taikhoan;
    private javax.swing.JButton welcome;
    // End of variables declaration//GEN-END:variables
}
