/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai_tap_lon;

import javax.swing.JOptionPane;

/**
 *
 * @author Nhuan's computer
 */
public class DangKiAdmin extends javax.swing.JFrame {

    
    
    
    /**
     * Creates new form NhapAdmin
     */
    public DangKiAdmin() {
        setLocation(this.getHeight() + 200, this.getWidth());
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nhaplaipass = new javax.swing.JPasswordField();
        matkhau = new javax.swing.JPasswordField();
        dangnhap = new javax.swing.JButton();
        dangki = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        SDT = new javax.swing.JTextField();
        hoten = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        Backgroud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng kí tài khoản quản trị viên");

        jPanel1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(210, 520, 150, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Số điện thoại");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(210, 460, 150, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Họ tên");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(210, 390, 100, 24);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nhập lại mật khẩu");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(210, 320, 140, 22);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tài khoản");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 200, 100, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mật khẩu");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 260, 100, 17);
        jPanel1.add(nhaplaipass);
        nhaplaipass.setBounds(380, 310, 350, 40);
        jPanel1.add(matkhau);
        matkhau.setBounds(380, 250, 350, 40);

        dangnhap.setBackground(new java.awt.Color(255, 102, 0));
        dangnhap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dangnhap.setForeground(new java.awt.Color(255, 255, 255));
        dangnhap.setText("Đăng nhập");
        dangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangnhapActionPerformed(evt);
            }
        });
        jPanel1.add(dangnhap);
        dangnhap.setBounds(740, 640, 120, 35);

        dangki.setBackground(new java.awt.Color(255, 102, 0));
        dangki.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dangki.setForeground(new java.awt.Color(255, 255, 255));
        dangki.setText("Đăng kí");
        dangki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangkiActionPerformed(evt);
            }
        });
        jPanel1.add(dangki);
        dangki.setBounds(140, 630, 99, 35);
        jPanel1.add(email);
        email.setBounds(380, 510, 350, 40);
        jPanel1.add(SDT);
        SDT.setBounds(380, 440, 350, 40);
        jPanel1.add(hoten);
        hoten.setBounds(380, 380, 350, 40);
        jPanel1.add(id);
        id.setBounds(380, 190, 350, 40);

        Backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bai_tap_lon/Đăng ký ADMIN.png"))); // NOI18N
        jPanel1.add(Backgroud);
        Backgroud.setBounds(0, 0, 940, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //ấn vào đăng kí để đăng kí tài khoản admin
    private void dangkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangkiActionPerformed
        int dk=JOptionPane.showConfirmDialog(this,"Ban co muon dang ki", "Thanh Cong", JOptionPane.YES_NO_OPTION);
        if(dk!=JOptionPane.YES_OPTION)
            return;
        //công thức regex
        String resdt="^0(\\d{8}|\\d{9})$";
        String reemail="[a-z0-9]*(\\@(gmail)\\.(com))$";
        //biến check để kiểm tra
        boolean check=true;
        //kiểm tra tài khoản đã tồn tại chưa
        if(CSDL.statement_kiemtrataikhoan(id.getText())==true){
            JOptionPane.showMessageDialog(this, "Da ton tai tai khoan");
            check=false;
        }
        //kiểm tra 2 mật khẩu
        if(matkhau.getText().equalsIgnoreCase(nhaplaipass.getText())==false){
            JOptionPane.showMessageDialog(this, "2 mat khau khong giong nhau");
            check=false;
        }
        //kiểm tra định dạng sđt
        if(SDT.getText().matches(resdt)==false){
            JOptionPane.showMessageDialog(this, "Sai dinh dang so dien thoai");
            check=false;
        }
        //kiểm tra định dạng ngày sinh
        if(email.getText().matches(reemail)==false){
            JOptionPane.showMessageDialog(this, "Sai dinh dang email");
            check=false;
        }
        //kiểm tra xem đã nhập vào bảng tài khoản được chưa
        if(check==true){
            if(CSDL.insert_into_taikhoan(id.getText(), matkhau.getText(), "YES")==false){
                JOptionPane.showMessageDialog(this, "Dang ki that bai");
                check=false;
            }
        }
        if(check==true){
            if(CSDL.insert_into_admin(id.getText(), hoten.getText(), SDT.getText(), email.getText())){
                JOptionPane.showMessageDialog(this, "Dang ki thanh cong");
                DangNhapAdmin dnadmin=new DangNhapAdmin();
                dnadmin.setVisible(true);
                this.dispose();
            }
        }else{
            JOptionPane.showMessageDialog(this, "Dang ki that bai");
        }
    }//GEN-LAST:event_dangkiActionPerformed
    //ấn đăng nhập để trở về đăng nhập
    private void dangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangnhapActionPerformed
        DangNhapAdmin ad=new DangNhapAdmin();
        ad.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dangnhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKiAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKiAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKiAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKiAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangKiAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backgroud;
    private javax.swing.JTextField SDT;
    private javax.swing.JButton dangki;
    private javax.swing.JButton dangnhap;
    private javax.swing.JTextField email;
    private javax.swing.JTextField hoten;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField matkhau;
    private javax.swing.JPasswordField nhaplaipass;
    // End of variables declaration//GEN-END:variables
}
