/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai_tap_lon;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Nhuan's computer
 */
public class DangKi extends javax.swing.JFrame {
    /**
     * Creates new form DangKi
     */
    public DangKi() {
        setLocation(this.getHeight() + 200, this.getWidth());
        initComponents();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        id = new javax.swing.JTextField();
        dangki = new javax.swing.JButton();
        matkhau = new javax.swing.JPasswordField();
        nhaplaipass = new javax.swing.JPasswordField();
        hodem = new javax.swing.JTextField();
        ten = new javax.swing.JTextField();
        diachi = new javax.swing.JTextField();
        SDT = new javax.swing.JTextField();
        welcome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ngaySinhChooser = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Backgroud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Người dùng đăng kí");

        jPanel1.setLayout(null);

        id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(id);
        id.setBounds(360, 180, 370, 30);

        dangki.setBackground(new java.awt.Color(255, 102, 0));
        dangki.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dangki.setForeground(new java.awt.Color(255, 255, 255));
        dangki.setText("Đăng kí");
        dangki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangkiActionPerformed(evt);
            }
        });
        jPanel1.add(dangki);
        dangki.setBounds(730, 640, 140, 38);

        matkhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(matkhau);
        matkhau.setBounds(360, 240, 370, 30);

        nhaplaipass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(nhaplaipass);
        nhaplaipass.setBounds(360, 300, 370, 30);

        hodem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(hodem);
        hodem.setBounds(360, 360, 370, 30);

        ten.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(ten);
        ten.setBounds(360, 410, 370, 30);

        diachi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(diachi);
        diachi.setBounds(360, 520, 370, 30);

        SDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(SDT);
        SDT.setBounds(360, 570, 370, 30);

        welcome.setBackground(new java.awt.Color(255, 102, 0));
        welcome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        welcome.setForeground(new java.awt.Color(255, 255, 255));
        welcome.setText("Welcome");
        welcome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                welcomeActionPerformed(evt);
            }
        });
        jPanel1.add(welcome);
        welcome.setBounds(440, 640, 110, 38);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tên tài khoản");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 180, 150, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mật khẩu");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(200, 240, 140, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nhập lại mật khẩu");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(200, 300, 140, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Họ đệm");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(200, 370, 140, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tên");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(200, 420, 140, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ngày sinh");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(200, 480, 140, 17);

        ngaySinhChooser.setForeground(new java.awt.Color(255, 255, 255));
        ngaySinhChooser.setDateFormatString("dd-MM-yyyy");
        jPanel1.add(ngaySinhChooser);
        ngaySinhChooser.setBounds(360, 470, 370, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Địa chỉ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(200, 530, 140, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Số điện thoại");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(200, 580, 140, 17);

        Backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bai_tap_lon/Đăng ký.png"))); // NOI18N
        jPanel1.add(Backgroud);
        Backgroud.setBounds(0, 0, 940, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 941, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //ấn vào đăng kí và đưa dữ liệu về bảng user
    private void dangkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangkiActionPerformed
        int dk=JOptionPane.showConfirmDialog(this,"Ban co muon dang ki", "Thanh Cong", JOptionPane.YES_NO_OPTION);
        if(dk!=JOptionPane.YES_OPTION)
            return;
        //công thức regex
        String resdt="^0(\\d{8}|\\d{9})$";
        String rengay="^\\d{2}[-|\\/]\\d{2}[-|\\/]\\d{4}$";
        //biến check để kiểm tra
        boolean check=true;
        //kiểm tra tài khoản đã tồn tại chưa
        if(CSDL.statement_kiemtrataikhoan(id.getText())==true){
            JOptionPane.showMessageDialog(this, "Da ton tai tai khoan");
            check=false;
        }
        //kiểm tra 2 mật khẩu
        if(matkhau.getText().equalsIgnoreCase(nhaplaipass.getText())==false){
            JOptionPane.showMessageDialog(this, "2 mat khau khong giong nhau");
            check=false;
        }
        //kiểm tra định dạng sđt
        if(SDT.getText().matches(resdt)==false){
            JOptionPane.showMessageDialog(this, "Sai dinh dang so dien thoai");
            check=false;
        }
        //kiểm tra định dạng ngày sinh
//        if(ngaysinh.getText().matches(rengay)==false){
//            JOptionPane.showMessageDialog(this, "Sai dinh dang ngay sinh");
//            check=false;
//        }
        //kiểm tra xem đã nhập vào bảng tài khoản được chưa
        if(check==true){
            if(CSDL.insert_into_taikhoan(id.getText(), matkhau.getText(), "NO")==false){
                JOptionPane.showMessageDialog(this, "Dang ki that bai");
                check=false;
            }
        }
        //kiểm tra xem đã nhập vào bảng người dùng được chưa
        if(check==true){
            DateFormat df = new SimpleDateFormat("dd-MM-yyyy");
            String s1 = df.format(ngaySinhChooser.getDate());
            if(CSDL.insert_into_user(id.getText(), hodem.getText(), ten.getText(), s1, diachi.getText(), SDT.getText())==true){
                JOptionPane.showMessageDialog(this, "Dang ki thanh cong");
                DangNhap dn=new DangNhap();
                dn.setVisible(true);
                this.dispose();
            }else JOptionPane.showMessageDialog(this, "Dang ki that bai");
        }else JOptionPane.showMessageDialog(this, "Dang ki that bai");
    }//GEN-LAST:event_dangkiActionPerformed
    //ấn vào welcom trở về welcome
    private void welcomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_welcomeActionPerformed
        Welcome wel=new Welcome();
        wel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_welcomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangKi().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backgroud;
    private javax.swing.JTextField SDT;
    private javax.swing.JButton dangki;
    private javax.swing.JTextField diachi;
    private javax.swing.JTextField hodem;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField matkhau;
    private com.toedter.calendar.JDateChooser ngaySinhChooser;
    private javax.swing.JPasswordField nhaplaipass;
    private javax.swing.JTextField ten;
    private javax.swing.JButton welcome;
    // End of variables declaration//GEN-END:variables
}