/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai_tap_lon;

import java.io.IOException;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author tungb
 */
public class GoiYCheDoLuyenTap extends javax.swing.JFrame {

    private Vector<String> prac;
    
    /**
     * Creates new form GoiYCheDoLuyenTap
     */
    public GoiYCheDoLuyenTap() throws SQLException, IOException {
        setLocation(this.getHeight() + 200, this.getWidth());
        initComponents();
        
        this.write();
    }

    
    public void write() throws SQLException, IOException {
        this.prac = new Vector<>();
        this.prac.addAll(CSDL.statement_luyen_tap_dinh_duong());
        this.theTrangDisplay.setText(this.prac.get(0));
        this.luyenTapDisplay.setText(this.prac.get(1));
        this.luyenTapDisplay.setWrapStyleWord(true);
        this.luyenTapDisplay.setLineWrap(true);
        this.luyenTapDisplay.setEditable(false);
        this.dinhDuongDisplay.setText(this.prac.get(2));
        this.dinhDuongDisplay.setWrapStyleWord(true);
        this.dinhDuongDisplay.setLineWrap(true);
        this.dinhDuongDisplay.setEditable(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        headerLuyenTap = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        theTrang = new javax.swing.JLabel();
        theTrangDisplay = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        luyenTapDisplay = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        dinhDuongDisplay = new javax.swing.JTextArea();
        Backgroud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        headerLuyenTap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerLuyenTap.setForeground(new java.awt.Color(255, 255, 255));
        headerLuyenTap.setText("Luyện Tập");
        jPanel1.add(headerLuyenTap);
        headerLuyenTap.setBounds(80, 260, 88, 25);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dinh Dưỡng");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 480, 110, 25);

        theTrang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        theTrang.setForeground(new java.awt.Color(255, 255, 255));
        theTrang.setText("Thể trạng");
        jPanel1.add(theTrang);
        theTrang.setBounds(80, 180, 100, 30);

        theTrangDisplay.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(theTrangDisplay);
        theTrangDisplay.setBounds(220, 180, 320, 30);

        back.setBackground(new java.awt.Color(255, 102, 0));
        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setText("Back");
        back.setMaximumSize(new java.awt.Dimension(80, 33));
        back.setMinimumSize(new java.awt.Dimension(80, 33));
        back.setPreferredSize(new java.awt.Dimension(80, 33));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(40, 110, 80, 33);

        luyenTapDisplay.setColumns(20);
        luyenTapDisplay.setRows(5);
        jScrollPane1.setViewportView(luyenTapDisplay);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(220, 270, 580, 190);

        dinhDuongDisplay.setColumns(20);
        dinhDuongDisplay.setRows(5);
        jScrollPane2.setViewportView(dinhDuongDisplay);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(220, 490, 580, 190);

        Backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bai_tap_lon/gợi ý chế độ luyện tập, dinh dưỡng.png"))); // NOI18N
        jPanel1.add(Backgroud);
        Backgroud.setBounds(0, 0, 940, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 941, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        TrangChuUser trangchu=new TrangChuUser();
        trangchu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GoiYCheDoLuyenTap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GoiYCheDoLuyenTap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GoiYCheDoLuyenTap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GoiYCheDoLuyenTap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GoiYCheDoLuyenTap().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(GoiYCheDoLuyenTap.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(GoiYCheDoLuyenTap.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backgroud;
    private javax.swing.JButton back;
    private javax.swing.JTextArea dinhDuongDisplay;
    private javax.swing.JLabel headerLuyenTap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea luyenTapDisplay;
    private javax.swing.JLabel theTrang;
    private javax.swing.JLabel theTrangDisplay;
    // End of variables declaration//GEN-END:variables
}
