/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai_tap_lon;

import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author tungb
 */
public class HienThiThongTinNguoiDung extends javax.swing.JFrame {
    
    private Vector<String> info;
    
    /**
     * Creates new form HienThiThongTinNguoiDung
     * @throws java.io.IOException
     */
    public HienThiThongTinNguoiDung() throws IOException, ParseException, SQLException {
        setLocation(this.getHeight() + 200, this.getWidth());
        initComponents();
        this.setInfo();
    }

    
    private void setInfo() throws IOException, ParseException, SQLException {
        this.info = new Vector<>();
        info.addAll(CSDL.statement_hien_thi_thong_tin_nguoi_dung());
        this.hoVaTenDisplay.setText(this.info.get(1) + " " + this.info.get(2));
        this.dobDisplay.setText(this.info.get(3));
        this.addressDisplay.setText(this.info.get(4));
        this.phoneDisplay.setText(this.info.get(5));
        this.chieuCaoDisplay.setText(this.info.get(6) + "   cm");
        this.canNangDisplay.setText(this.info.get(7) + "   kg");
        this.bmiDisplay.setText(this.info.get(8));
        this.theTrangDisplay.setText(this.info.get(9));
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hoVaTen = new javax.swing.JLabel();
        ngaySinh = new javax.swing.JLabel();
        diaChi = new javax.swing.JLabel();
        sdt = new javax.swing.JLabel();
        bmi = new javax.swing.JLabel();
        chieuCao = new javax.swing.JLabel();
        canNang = new javax.swing.JLabel();
        hoVaTenDisplay = new javax.swing.JLabel();
        bmiDisplay = new javax.swing.JLabel();
        dobDisplay = new javax.swing.JLabel();
        addressDisplay = new javax.swing.JLabel();
        phoneDisplay = new javax.swing.JLabel();
        chieuCaoDisplay = new javax.swing.JLabel();
        canNangDisplay = new javax.swing.JLabel();
        edit = new javax.swing.JButton();
        theTrang = new javax.swing.JLabel();
        theTrangDisplay = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(880, 600));

        jPanel1.setLayout(null);

        hoVaTen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hoVaTen.setForeground(new java.awt.Color(255, 255, 255));
        hoVaTen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hoVaTen.setText("Họ Và Tên");
        jPanel1.add(hoVaTen);
        hoVaTen.setBounds(50, 280, 89, 33);

        ngaySinh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ngaySinh.setForeground(new java.awt.Color(255, 255, 255));
        ngaySinh.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ngaySinh.setText("Ngày Sinh");
        jPanel1.add(ngaySinh);
        ngaySinh.setBounds(50, 350, 89, 33);

        diaChi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        diaChi.setForeground(new java.awt.Color(255, 255, 255));
        diaChi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        diaChi.setText("Địa Chỉ");
        jPanel1.add(diaChi);
        diaChi.setBounds(50, 420, 89, 33);

        sdt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sdt.setForeground(new java.awt.Color(255, 255, 255));
        sdt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sdt.setText("Số Điện Thoại");
        jPanel1.add(sdt);
        sdt.setBounds(50, 480, 110, 33);

        bmi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bmi.setForeground(new java.awt.Color(255, 255, 255));
        bmi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bmi.setText("BMI");
        jPanel1.add(bmi);
        bmi.setBounds(50, 680, 89, 33);

        chieuCao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chieuCao.setForeground(new java.awt.Color(255, 255, 255));
        chieuCao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chieuCao.setText("Chiều Cao");
        jPanel1.add(chieuCao);
        chieuCao.setBounds(50, 550, 89, 33);

        canNang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        canNang.setForeground(new java.awt.Color(255, 255, 255));
        canNang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        canNang.setText("Cân Nặng");
        jPanel1.add(canNang);
        canNang.setBounds(50, 610, 89, 33);

        hoVaTenDisplay.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        hoVaTenDisplay.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(hoVaTenDisplay);
        hoVaTenDisplay.setBounds(190, 280, 563, 33);

        bmiDisplay.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        bmiDisplay.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(bmiDisplay);
        bmiDisplay.setBounds(190, 680, 149, 33);

        dobDisplay.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        dobDisplay.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(dobDisplay);
        dobDisplay.setBounds(190, 350, 563, 33);

        addressDisplay.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        addressDisplay.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(addressDisplay);
        addressDisplay.setBounds(190, 420, 563, 33);

        phoneDisplay.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        phoneDisplay.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(phoneDisplay);
        phoneDisplay.setBounds(190, 480, 563, 33);

        chieuCaoDisplay.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        chieuCaoDisplay.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(chieuCaoDisplay);
        chieuCaoDisplay.setBounds(190, 550, 563, 33);

        canNangDisplay.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        canNangDisplay.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(canNangDisplay);
        canNangDisplay.setBounds(190, 610, 563, 33);

        edit.setBackground(new java.awt.Color(230, 94, 48));
        edit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit);
        edit.setBounds(810, 200, 80, 33);

        theTrang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        theTrang.setForeground(new java.awt.Color(255, 255, 255));
        theTrang.setText("Thể Trạng");
        jPanel1.add(theTrang);
        theTrang.setBounds(410, 680, 80, 33);

        theTrangDisplay.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        theTrangDisplay.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(theTrangDisplay);
        theTrangDisplay.setBounds(510, 680, 213, 33);

        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setText("Back");
        back.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        back.setMaximumSize(new java.awt.Dimension(72, 33));
        back.setMinimumSize(new java.awt.Dimension(72, 33));
        back.setPreferredSize(new java.awt.Dimension(72, 33));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(50, 200, 80, 33);

        Clear.setBackground(new java.awt.Color(230, 94, 48));
        Clear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Clear.setText("Xóa Tài Khoản");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel1.add(Clear);
        Clear.setBounds(740, 690, 120, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bai_tap_lon/Admin2.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 940, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        try {
            // TODO add your handling code here:
            ChinhSuaThongTinNguoiDung edit = new ChinhSuaThongTinNguoiDung();
            edit.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(HienThiThongTinNguoiDung.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(HienThiThongTinNguoiDung.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(HienThiThongTinNguoiDung.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        TrangChuUser trangchu=new TrangChuUser();
        trangchu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        try {
            CSDL.statement_xoa_tk();
        } catch (SQLException ex) {
            Logger.getLogger(HienThiThongTinNguoiDung.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(HienThiThongTinNguoiDung.class.getName()).log(Level.SEVERE, null, ex);
        }
        Welcome wel = new Welcome();
        wel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ClearActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HienThiThongTinNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HienThiThongTinNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HienThiThongTinNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HienThiThongTinNguoiDung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new HienThiThongTinNguoiDung().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(HienThiThongTinNguoiDung.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(HienThiThongTinNguoiDung.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(HienThiThongTinNguoiDung.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JLabel addressDisplay;
    private javax.swing.JButton back;
    private javax.swing.JLabel bmi;
    private javax.swing.JLabel bmiDisplay;
    private javax.swing.JLabel canNang;
    private javax.swing.JLabel canNangDisplay;
    private javax.swing.JLabel chieuCao;
    private javax.swing.JLabel chieuCaoDisplay;
    private javax.swing.JLabel diaChi;
    private javax.swing.JLabel dobDisplay;
    private javax.swing.JButton edit;
    private javax.swing.JLabel hoVaTen;
    private javax.swing.JLabel hoVaTenDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel ngaySinh;
    private javax.swing.JLabel phoneDisplay;
    private javax.swing.JLabel sdt;
    private javax.swing.JLabel theTrang;
    private javax.swing.JLabel theTrangDisplay;
    // End of variables declaration//GEN-END:variables
}
