/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai_tap_lon;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Nhap_Loi_Khuyen extends javax.swing.JFrame {

    /**
     * Creates new form Nhap_Loi_Khuyen
     */
    public Nhap_Loi_Khuyen() {
        setLocation(this.getHeight() + 200, this.getWidth());
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cacloaithetrang = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        nhaptapluyen = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        nhapdinhduong = new javax.swing.JTextArea();
        luuthongtin = new javax.swing.JButton();
        trove = new javax.swing.JButton();
        Backgroud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        cacloaithetrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn", "Béo phì độ I", "Béo phì độ II", "Béo phì độ III", "Bình thường", "Gầy độ 1", "Gầy độ 2", "Gầy độ 3", "Thừa cân" }));
        cacloaithetrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cacloaithetrangActionPerformed(evt);
            }
        });
        jPanel1.add(cacloaithetrang);
        cacloaithetrang.setBounds(310, 190, 240, 30);

        nhaptapluyen.setColumns(20);
        nhaptapluyen.setRows(5);
        jScrollPane1.setViewportView(nhaptapluyen);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(310, 270, 420, 170);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Thể Trạng");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 190, 100, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tập Luyện");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 270, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dinh Dưỡng");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(150, 460, 120, 20);

        nhapdinhduong.setColumns(20);
        nhapdinhduong.setRows(5);
        jScrollPane2.setViewportView(nhapdinhduong);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(310, 460, 420, 170);

        luuthongtin.setBackground(new java.awt.Color(255, 102, 0));
        luuthongtin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        luuthongtin.setText("Lưu thông tin");
        luuthongtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuthongtinActionPerformed(evt);
            }
        });
        jPanel1.add(luuthongtin);
        luuthongtin.setBounds(730, 650, 140, 30);

        trove.setBackground(new java.awt.Color(255, 102, 0));
        trove.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        trove.setText("Trở về");
        trove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                troveActionPerformed(evt);
            }
        });
        jPanel1.add(trove);
        trove.setBounds(170, 650, 130, 30);

        Backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bai_tap_lon/NHập lời khuyên.png"))); // NOI18N
        jPanel1.add(Backgroud);
        Backgroud.setBounds(0, 0, 940, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 941, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cacloaithetrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cacloaithetrangActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cacloaithetrangActionPerformed

    private String getTime(){
        LocalDateTime myDateObj = LocalDateTime.now();
        DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");

        String formattedDate = myDateObj.format(myFormatObj);
        return formattedDate;
    }
    
    
    private void luuthongtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuthongtinActionPerformed
        // TODO add your handling code here:
        
        //dialog
        int dk=JOptionPane.showConfirmDialog(this,"Bạn có muốn lưu thông tin","Đồng ý",JOptionPane.YES_NO_CANCEL_OPTION);
        if(dk!=JOptionPane.YES_OPTION) return;
        
        
        //lay id admin
        String admin="";
        try {
            admin = CSDL.ReadIDFromFile();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Them_Trung_Tam.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Them_Trung_Tam.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        //lay the trang
        int index=cacloaithetrang.getSelectedIndex();
        String value="";
        if(index>0){
            value=cacloaithetrang.getItemAt(index);
        }
        
        
        
        //luu vao sql
        if(CSDL.update_loi_khuyen(value , nhaptapluyen.getText() , nhapdinhduong.getText() ) && CSDL.insert_into_cap_nhat_loi_khuyen(admin,value,getTime())){
            TrangChuAdmin back = new TrangChuAdmin();
            back.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "Mời bạn nhập lại thông tin");
        }
        
        
        
    }//GEN-LAST:event_luuthongtinActionPerformed

    private void troveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_troveActionPerformed
        // TODO add your handling code here:
        TrangChuAdmin back=new TrangChuAdmin();
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_troveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nhap_Loi_Khuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nhap_Loi_Khuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nhap_Loi_Khuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nhap_Loi_Khuyen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nhap_Loi_Khuyen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backgroud;
    private javax.swing.JComboBox<String> cacloaithetrang;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton luuthongtin;
    private javax.swing.JTextArea nhapdinhduong;
    private javax.swing.JTextArea nhaptapluyen;
    private javax.swing.JButton trove;
    // End of variables declaration//GEN-END:variables
}
