/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai_tap_lon;

import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Them_Trung_Tam extends javax.swing.JFrame {

    /**
     * Creates new form Them_Trung_Tam
     */
    public Them_Trung_Tam(){
        setLocation(this.getHeight() + 200, this.getWidth());

        initComponents();
    }
//    public Them_Trung_Tam(java.awt.Frame parent, boolean modal) {
//        super(parent, modal);
//        initComponents();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LuuThongTin = new javax.swing.JButton();
        QuayLai = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        matrungtam = new javax.swing.JTextField();
        tentrungtam = new javax.swing.JTextField();
        tinh = new javax.swing.JTextField();
        diachicuthe = new javax.swing.JTextField();
        sodienthoai = new javax.swing.JTextField();
        Backgroud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        LuuThongTin.setBackground(new java.awt.Color(255, 102, 0));
        LuuThongTin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LuuThongTin.setText("Lưu thông tin");
        LuuThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuuThongTinActionPerformed(evt);
            }
        });
        jPanel1.add(LuuThongTin);
        LuuThongTin.setBounds(730, 640, 140, 30);

        QuayLai.setBackground(new java.awt.Color(255, 102, 0));
        QuayLai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        QuayLai.setText("Quay lại");
        QuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuayLaiActionPerformed(evt);
            }
        });
        jPanel1.add(QuayLai);
        QuayLai.setBounds(180, 650, 90, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mã Trung Tâm");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 220, 140, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tên Trung Tâm");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 277, 140, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tỉnh-Thành Phố");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(250, 360, 150, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Địa Chỉ Cụ Thể");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(250, 420, 140, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Số Điện Thoại Liên Hệ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(250, 490, 170, 17);

        matrungtam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrungtamActionPerformed(evt);
            }
        });
        jPanel1.add(matrungtam);
        matrungtam.setBounds(460, 210, 260, 30);
        jPanel1.add(tentrungtam);
        tentrungtam.setBounds(460, 280, 260, 30);
        jPanel1.add(tinh);
        tinh.setBounds(460, 350, 260, 30);
        jPanel1.add(diachicuthe);
        diachicuthe.setBounds(460, 410, 260, 30);
        jPanel1.add(sodienthoai);
        sodienthoai.setBounds(460, 480, 260, 30);

        Backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bai_tap_lon/cập nhật thông tin trung tâm.png"))); // NOI18N
        jPanel1.add(Backgroud);
        Backgroud.setBounds(0, 0, 940, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matrungtamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrungtamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matrungtamActionPerformed
    
    //lay time
    private String getTime(){
        LocalDateTime myDateObj = LocalDateTime.now();
        DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");

        String formattedDate = myDateObj.format(myFormatObj);
        return formattedDate;
    }
    
    
    //luu thong tin
    private void LuuThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuuThongTinActionPerformed
        // TODO add your handling code here:
        
        
        int dk=JOptionPane.showConfirmDialog(this,"Bạn có muốn lưu thông tin","Đồng ý",JOptionPane.YES_NO_CANCEL_OPTION);
        if(dk!=JOptionPane.YES_OPTION) return;
        
        
        //lay id admin
        String s="";
        try {
            s = CSDL.ReadIDFromFile();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Them_Trung_Tam.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Them_Trung_Tam.class.getName()).log(Level.SEVERE, null, ex);
        }
        //thao tac
        if(CSDL.insert_into_trungtam(matrungtam.getText(), tentrungtam.getText(), tinh.getText(), diachicuthe.getText(), sodienthoai.getText())&&CSDL.insert_into_capnhattrungtam(s, matrungtam.getText(), getTime())){
            
            TrangChuAdmin back = new TrangChuAdmin();
            back.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "Mời bạn nhập lại thông tin");
        }
    }//GEN-LAST:event_LuuThongTinActionPerformed

    private void QuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuayLaiActionPerformed
        // TODO add your handling code here:
        TrangChuAdmin back = new TrangChuAdmin();
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_QuayLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Them_Trung_Tam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Them_Trung_Tam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Them_Trung_Tam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Them_Trung_Tam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Them_Trung_Tam().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backgroud;
    private javax.swing.JButton LuuThongTin;
    private javax.swing.JButton QuayLai;
    private javax.swing.JTextField diachicuthe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField matrungtam;
    private javax.swing.JTextField sodienthoai;
    private javax.swing.JTextField tentrungtam;
    private javax.swing.JTextField tinh;
    // End of variables declaration//GEN-END:variables
}
