/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai_tap_lon;

import javax.swing.JOptionPane;

/**
 *
 * @author Nhuan's computer
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Welcome() {
        setLocation(this.getHeight() + 200, this.getWidth());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dangnhap = new javax.swing.JButton();
        dangki = new javax.swing.JButton();
        nhapma = new javax.swing.JButton();
        Backgroud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bài Tập Lớn CSDL");
        setBackground(new java.awt.Color(0, 0, 51));

        jPanel1.setLayout(null);

        dangnhap.setBackground(new java.awt.Color(204, 51, 0));
        dangnhap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dangnhap.setForeground(new java.awt.Color(255, 255, 255));
        dangnhap.setText("Đăng nhập");
        dangnhap.setToolTipText("");
        dangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangnhapActionPerformed(evt);
            }
        });
        jPanel1.add(dangnhap);
        dangnhap.setBounds(570, 320, 290, 50);

        dangki.setBackground(new java.awt.Color(204, 51, 0));
        dangki.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dangki.setForeground(new java.awt.Color(255, 255, 255));
        dangki.setText("Đăng kí");
        dangki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangkiActionPerformed(evt);
            }
        });
        jPanel1.add(dangki);
        dangki.setBounds(570, 410, 290, 50);

        nhapma.setBackground(new java.awt.Color(204, 51, 0));
        nhapma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nhapma.setForeground(new java.awt.Color(255, 255, 255));
        nhapma.setText("Nhập mã");
        nhapma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhapmaActionPerformed(evt);
            }
        });
        jPanel1.add(nhapma);
        nhapma.setBounds(570, 490, 290, 50);

        Backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bai_tap_lon/welcome.png"))); // NOI18N
        jPanel1.add(Backgroud);
        Backgroud.setBounds(0, 0, 940, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //ấn vào đăng kí để tới đăng kí
    private void dangkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangkiActionPerformed
        DangKi dk=new DangKi();
        dk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dangkiActionPerformed
    //ấn vào đăng nhập để tới đăng nhập
    private void dangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangnhapActionPerformed
        DangNhap dn=new DangNhap();
        dn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dangnhapActionPerformed
    //ấn vào nhập mã để nhập mã kiểm tra admin
    private void nhapmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapmaActionPerformed
        NhapMa ma=new NhapMa();
        ma.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nhapmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backgroud;
    private javax.swing.JButton dangki;
    private javax.swing.JButton dangnhap;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nhapma;
    // End of variables declaration//GEN-END:variables
}
